
const API='https://www.e-solat.gov.my/index.php?r=esolatApi/takwimsolat&zone=SGR02&period=today';
const NAV=[['home','Utama'],['prayer','Waktu Solat'],['quran','e-Quran'],['kariah','Ahli Kariah'],['khairat','Khairat Kematian'],['finance','Maklumat Kewangan'],['documents','Dokumen'],['org','Carta Organisasi']];
const roles=[['Pengerusi',1],['Timbalan Pengerusi',1],['Imam',5],['Bilal',5],['Siak',5],['Setiausaha',1],['Penolong Setiausaha',1],['Bendahari',1],['Penolong Bendahari',1],['Jawatankuasa',6],['Wakil Pemuda',1],['Wakil Muslimat',1],['Pemeriksa Kira-kira',2]];
const roleOptions=roles.flatMap(([r,n])=>Array.from({length:n},(_,i)=>n>1?`${r} ${i+1}`:r));
const defaults={theme:'emerald',light:false,fontScale:1,marqueeSpeed:24,announcement:'Selamat datang ke Surau Ar-Raudhah Eristana.',pages:{prayer:true,quran:true,kariah:true,khairat:true,finance:true,documents:true,org:true},media:[],events:[],people:[],funds:[{name:'Dana Umum',balance:0},{name:'Dana Pembangunan',balance:0},{name:'Dana Kelas Ngaji',balance:0},{name:'Dana Qurban',balance:0}],documents:[],treasurerPhone:'60123456789',githubRepo:'suraueristana/main'};
const themes={emerald:['#071812','#0d271d','#22c55e','#f7c654'],blue:['#071522','#10283d','#38bdf8','#fbbf24'],maroon:['#21090f','#3a101b','#fb7185','#fbbf24'],purple:['#170b25','#29143d','#c084fc','#facc15']};
let state={...defaults,pages:{...defaults.pages}},page='home',prayers=[],slide=0,slideTimer=null,adminSession=null;
const $=q=>document.querySelector(q),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function applyTheme(){let t=themes[state.theme]||themes.emerald;let dark=state.light?['#eef7f2','#fff','#10231b','#5f746a']:[t[0],t[1],'#f5fff9','#acc3b6'];document.documentElement.style.cssText=`--bg:${dark[0]};--panel:${dark[1]};--text:${dark[2]};--muted:${dark[3]};--primary:${t[2]};--accent:${t[3]};--scale:${state.fontScale};--marquee:${state.marqueeSpeed}s`}
async function save(){localStorage.setItem('arraudhahB',JSON.stringify(state));try{if(await surauDb.session())await surauDb.saveConfig(state)}catch(e){alert('Gagal simpan ke Supabase: '+e.message)}applyTheme();render()}
function fmt12(t){if(!t)return'-';let[h,m]=t.split(':').map(Number);return`${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`}
function header(){return`<header class="header"><img class="logo" src="assets/LOGO AR RAUDHAH 2023-07.png" alt="Logo"><div class="identity"><h1>SURAU AR-RAUDHAH ERISTANA</h1><p>No.1, Eristana, Persiaran Seri Pristana 1, Seri Pristana, 47000 Sungai Buloh, Selangor · JAI.SEL.BPM/01/037/197</p></div><nav class="nav">${NAV.filter(([id])=>id==='home'||state.pages[id]).map(([id,l])=>`<button class="btn ${page===id?'active':''}" onclick="go('${id}')">${l}</button>`).join('')}</nav><button class="btn" onclick="font(-1)">A-</button><button class="btn" onclick="font(1)">A+</button><button class="btn" onclick="state.light=!state.light;save()">◐</button><button class="btn primary" onclick="openAdmin()">⚙</button></header>`}
function render(){let body={home:homePage,prayer:prayerPage,quran:quranPage,kariah:()=>memberPage('kariah'),khairat:()=>memberPage('khairat'),finance:financePage,documents:documentsPage,org:orgPage}[page]?.()||homePage();$('#app').innerHTML=header()+`<main class="main">${body}</main>`+(page==='home'?`<div class="marquee"><strong>📢 PENGUMUMAN</strong><div class="marquee-track"><span>${esc(state.announcement)}</span></div></div>`:'');if(page==='home'){renderPrayerList();renderMedia();clock()}}
function go(p){page=p;render()}function font(d){state.fontScale=Math.max(.8,Math.min(1.3,+((state.fontScale||1)+d*.1).toFixed(1)));save()}
function homePage(){let ev=[...(state.events||[])].filter(e=>new Date(e.date+'T23:59:59')>=new Date()).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,2);return`<div class="grid home"><section><div class="card"><div id="clock" class="clock">--:--:--</div><div id="date" class="muted" style="text-align:center"></div><div id="hijri" class="accent" style="text-align:center;font-weight:800"></div></div><div class="card" style="margin-top:16px"><b>Waktu Solat Hari Ini</b><small id="apiState" class="muted" style="float:right">SGR02</small><div id="prayerList"></div><div id="nextPrayer" class="notice">Memuatkan...</div></div><div class="card" style="margin-top:16px"><b>Peristiwa Penting</b>${ev.length?ev.map(e=>`<div class="event"><span><b>${esc(e.name)}</b><br><small class="muted">${new Date(e.date+'T00:00:00+08:00').toLocaleDateString('ms-MY',{day:'numeric',month:'long',year:'numeric'})}</small></span><span class="big">${Math.max(0,Math.ceil((new Date(e.date+'T00:00:00+08:00')-new Date())/86400000))}<small style="font-size:11px"> hari</small></span></div>`).join(''):'<p class="muted">Belum ada peristiwa akan datang.</p>'}</div></section><section class="card media" id="media"></section></div>`}
function clock(){let n=new Date(),o={timeZone:'Asia/Kuala_Lumpur'};if($('#clock')){$('#clock').textContent=n.toLocaleTimeString('en-MY',{...o,hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true});$('#date').textContent='GMT+8 · '+n.toLocaleDateString('ms-MY',{...o,weekday:'long',day:'numeric',month:'long',year:'numeric'});try{$('#hijri').textContent=new Intl.DateTimeFormat('ms-MY-u-ca-islamic',{...o,day:'numeric',month:'long',year:'numeric'}).format(n)}catch{}}updatePrayerHighlight()}
async function loadPrayer(){try{let r=await fetch(API,{cache:'no-store'}),j=await r.json(),d=j.prayerTime?.[0];if(!d)throw Error('Format API');prayers=[['Imsak',d.imsak],['Subuh',d.fajr],['Syuruk',d.syuruk],['Zohor',d.dhuhr],['Asar',d.asr],['Maghrib',d.maghrib],['Isyak',d.isha]].map(([name,time])=>({name,time:time.slice(0,5)}));localStorage.setItem('prayerCache',JSON.stringify(prayers));if($('#apiState'))$('#apiState').textContent='Langsung · SGR02'}catch(e){prayers=JSON.parse(localStorage.getItem('prayerCache')||'[]');if($('#apiState'))$('#apiState').textContent=prayers.length?'Cache · SGR02':'API tidak tersedia'}renderPrayerList()}
function renderPrayerList(){if(!$('#prayerList'))return;$('#prayerList').innerHTML=prayers.length?prayers.map(p=>`<div class="prayer" data-time="${p.time}"><b>${p.name}</b><b>${fmt12(p.time)}</b></div>`).join(''):'<p class="muted">Waktu solat sedang dimuatkan.</p>';updatePrayerHighlight()}
function updatePrayerHighlight(){if(!prayers.length||!$('#nextPrayer'))return;let n=new Date(),mins=n.getHours()*60+n.getMinutes(),idx=prayers.findIndex((p,i)=>i>0&&p.time.split(':').reduce((a,b)=>a*60+Number(b))>mins);if(idx<0)idx=1;document.querySelectorAll('.prayer').forEach((e,i)=>e.classList.toggle('next',i===idx));$('#nextPrayer').textContent=`Solat seterusnya: ${prayers[idx].name} · ${fmt12(prayers[idx].time)}`}
function renderMedia(){clearTimeout(slideTimer);let el=$('#media');if(!el)return;let media=state.media||[];if(!media.length){el.innerHTML='<div style="text-align:center"><div style="font-size:70px">🕌</div><h2>Selamat Datang</h2><p class="muted">Media GitHub akan dipaparkan di sini.</p></div>';return}slide%=media.length;let m=media[slide];el.innerHTML=(m.type==='video'?`<video src="${esc(m.url)}" autoplay muted controls onended="nextSlide()"></video>`:`<img src="${esc(m.url)}" alt="Media">`)+(m.caption?`<div class="caption">${esc(m.caption)}</div>`:'');if(m.type!=='video')slideTimer=setTimeout(nextSlide,10000)}function nextSlide(){slide=(slide+1)%state.media.length;renderMedia()}
function prayerPage(){return`<h2 class="page-title">Waktu Solat</h2><p class="muted">Jadual e-Solat JAKIM · SGR02</p><div class="grid tiles">${prayers.map(p=>`<div class="card"><span class="muted">${p.name}</span><div class="big">${fmt12(p.time)}</div></div>`).join('')||'<div class="card">Memuatkan waktu solat...</div>'}</div>`}
function quranPage(){return`<h2 class="page-title">e-Quran</h2><div class="card"><div class="notice"><b>Fasa integrasi seterusnya</b><br>Quran Foundation memerlukan backend/serverless untuk melindungi kelayakan aplikasi.</div><p>Halaman pembaca, surah, terjemahan dan audio akan diaktifkan selepas API backend dikonfigurasi.</p></div>`}
function memberPage(type){let title=type==='kariah'?'Ahli Kariah':'Khairat Kematian';return`<h2 class="page-title">${title}</h2><p class="muted">Carian tepat menggunakan No. IC</p><div class="search"><input id="memberIC" placeholder="No. IC tanpa sengkang"><button class="btn primary" onclick="findMember('${type}')">Cari</button></div><div id="memberResult" class="card">Masukkan No. IC untuk semakan.</div>`}
async function findMember(type){let ic=$('#memberIC').value.trim();if(!ic)return;$('#memberResult').innerHTML='Mencari...';let{data,error}=await surauDb.lookup(type,ic);if(error)return $('#memberResult').innerHTML=`<div class="error">${esc(error.message)}</div>`;let x=data?.[0];$('#memberResult').innerHTML=x?`<h3>${esc(x.full_name)}</h3><p>Status: <b>${esc(x.status)}</b></p>${x.house?`<p>Rumah: ${esc(x.house)}</p>`:''}${x.last_payment?`<p>Bayaran terakhir: ${esc(x.last_payment)}</p>`:''}${x.expiry_date?`<p>Tarikh tamat: ${esc(x.expiry_date)}</p>`:''}${type==='khairat'?`<a class="btn primary" target="_blank" href="https://wa.me/${esc(state.treasurerPhone)}?text=Saya ingin memperbaharui keahlian Khairat Kematian">WhatsApp Bendahari</a>`:''}`:'<h3>Rekod tidak dijumpai</h3><p>Sila hubungi pentadbir untuk pendaftaran atau kemas kini.</p>'}
function financePage(){return`<h2 class="page-title">Maklumat Kewangan</h2><div class="grid tiles">${(state.funds||[]).map(f=>`<div class="card"><span class="muted">${esc(f.name)}</span><div class="big">${new Intl.NumberFormat('ms-MY',{style:'currency',currency:'MYR'}).format(+f.balance||0)}</div></div>`).join('')||'<div class="card">Belum dikemas kini.</div>'}</div>`}
function documentsPage(){let docs=(state.documents||[]).filter(d=>d.visibility==='public');return`<h2 class="page-title">Dokumen</h2>${docs.map(d=>`<div class="card" style="margin-bottom:8px"><b>${esc(d.name)}</b><a class="btn primary" style="float:right" href="${esc(d.url)}" target="_blank">Buka</a><div class="muted">${esc(d.category||'Umum')}</div></div>`).join('')||'<div class="card">Belum ada dokumen awam.</div>'}`}
function orgPage(){return`<h2 class="page-title">Carta Organisasi</h2><div class="grid org">${(state.people||[]).map(p=>`<div class="card person">${p.photo?`<img src="${esc(p.photo)}" alt="Foto">`:'<div style="font-size:60px">👤</div>'}<div class="accent"><b>${esc(p.role)}</b></div><h3>${esc(p.name)}</h3><small>${esc(p.house||'')}<br>${esc(p.phone||'')}<br>${esc(p.task||'')}</small></div>`).join('')||'<div class="card">Belum dikemas kini.</div>'}</div>`}
async function openAdmin(){adminSession=await surauDb.session();if(adminSession)return admin();document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="loginModal"><div class="modal-box" style="max-width:480px"><div class="modal-head"><h2>Log Masuk Pentadbir</h2><button class="btn" onclick="$('#loginModal').remove()">✕</button></div><div class="modal-body login"><div class="field"><label>E-mel</label><input id="adminEmail" type="email"></div><div class="field" style="margin-top:10px"><label>Kata laluan</label><input id="adminPassword" type="password"></div><button class="btn primary" style="margin-top:12px;width:100%" onclick="adminLogin()">Log Masuk</button><div id="loginMsg"></div></div></div></div>`)}
async function adminLogin(){let{error}=await surauDb.signIn($('#adminEmail').value,$('#adminPassword').value);if(error)return $('#loginMsg').innerHTML=`<div class="error" style="margin-top:10px">${esc(error.message)}</div>`;$('#loginModal').remove();admin()}
function admin(){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="adminModal"><div class="modal-box"><div class="modal-head"><h2>Pentadbiran Portal</h2><div><button class="btn" onclick="adminLogout()">Log Keluar</button> <button class="btn" onclick="$('#adminModal').remove()">✕</button></div></div><div class="modal-body"><div class="tabs">${[['general','Portal'],['media','Media & GitHub'],['events','Peristiwa'],['org','Carta Organisasi'],['finance','Kewangan'],['docs','Dokumen']].map(([i,l])=>`<button class="btn" onclick="adminTab('${i}')">${l}</button>`).join('')}</div><div id="adminPane"></div></div></div></div>`);adminTab('general')}
async function adminLogout(){await surauDb.signOut();$('#adminModal').remove()}
function adminTab(t){let p=$('#adminPane');if(t==='general')p.innerHTML=`<div class="fields"><div class="field full"><label>Pengumuman</label><textarea id="ann">${esc(state.announcement)}</textarea></div><div class="field"><label>Kelajuan marquee (saat)</label><input id="speed" type="number" min="8" max="60" value="${state.marqueeSpeed}"></div><div class="field"><label>Tema warna</label><select id="theme">${Object.keys(themes).map(x=>`<option ${x===state.theme?'selected':''}>${x}</option>`).join('')}</select></div><div class="field full"><b>Aktif / Nyahaktif Halaman</b><br>${Object.keys(state.pages).map(k=>`<label style="display:inline-block;margin:8px"><input type="checkbox" data-page="${k}" ${state.pages[k]?'checked':''}> ${NAV.find(x=>x[0]===k)?.[1]}</label>`).join('')}</div><button class="btn primary" onclick="saveGeneral()">Simpan</button></div>`;else if(t==='media')p.innerHTML=`<div class="notice">Upload ke GitHub, kemudian masukkan URL raw fail di bawah.</div><p><a class="btn primary" target="_blank" href="https://github.com/${state.githubRepo}/upload/main/assets/media">Upload Media ke GitHub</a></p><div class="fields"><div class="field"><label>Jenis</label><select id="mType"><option value="image">Gambar</option><option value="video">Video</option></select></div><div class="field"><label>URL Raw GitHub</label><input id="mUrl"></div><div class="field"><label>Kapsyen</label><input id="mCap"></div><button class="btn primary" onclick="addMedia()">Tambah</button></div>${list(state.media,'media')}`;else if(t==='events')p.innerHTML=`<div class="fields"><input id="eName" placeholder="Nama peristiwa"><input id="eDate" type="date"><button class="btn primary" onclick="addEvent()">Tambah</button></div>${list(state.events,'events')}`;else if(t==='org')p.innerHTML=`<div class="fields"><div class="field"><label>Jawatan</label><select id="oRole" onchange="loadRole()">${roleOptions.map(x=>`<option>${x}</option>`).join('')}</select></div>${['name','house','phone','photo','task'].map(k=>`<div class="field"><label>${{name:'Nama',house:'Rumah',phone:'No. Telefon',photo:'URL Foto',task:'Tugasan'}[k]}</label><input id="o_${k}"></div>`).join('')}<button class="btn primary" onclick="saveRole()">Simpan / Kemas Kini</button></div>`;else if(t==='finance')p.innerHTML=(state.funds||[]).map((f,i)=>`<div class="fields" style="margin-bottom:8px"><input id="fn${i}" value="${esc(f.name)}"><input id="fb${i}" type="number" value="${f.balance}"></div>`).join('')+`<button class="btn primary" onclick="saveFunds()">Simpan</button>`;else p.innerHTML=`<div class="fields"><input id="dName" placeholder="Nama dokumen"><input id="dUrl" placeholder="URL GitHub"><input id="dCat" placeholder="Kategori"><select id="dVis"><option value="public">Awam</option><option value="admin">Pentadbir sahaja</option></select><button class="btn primary" onclick="addDoc()">Tambah</button></div>${list(state.documents,'documents')}`;if(t==='org')loadRole()}
function list(a,t){return`<div>${(a||[]).map((x,i)=>`<div class="item"><span>${esc(x.name||x.caption||x.url)}</span><button class="btn danger" onclick="removeItem('${t}',${i})">Padam</button></div>`).join('')}</div>`}
function saveGeneral(){state.announcement=$('#ann').value;state.marqueeSpeed=+$('#speed').value||24;state.theme=$('#theme').value;document.querySelectorAll('[data-page]').forEach(x=>state.pages[x.dataset.page]=x.checked);save();adminTab('general')}
function addMedia(){if(!$('#mUrl').value)return;state.media.push({type:$('#mType').value,url:$('#mUrl').value,caption:$('#mCap').value});save();adminTab('media')}
function addEvent(){if(!$('#eName').value||!$('#eDate').value)return;state.events.push({name:$('#eName').value,date:$('#eDate').value});save();adminTab('events')}
function removeItem(t,i){state[t].splice(i,1);save();adminTab(t)}
function loadRole(){let r=$('#oRole').value,x=state.people.find(v=>v.role===r)||{};['name','house','phone','photo','task'].forEach(k=>$(`#o_${k}`).value=x[k]||'')}
function saveRole(){let r=$('#oRole').value,x={role:r};['name','house','phone','photo','task'].forEach(k=>x[k]=$(`#o_${k}`).value);state.people=state.people.filter(v=>v.role!==r);state.people.push(x);save();adminTab('org')}
function saveFunds(){state.funds=state.funds.map((f,i)=>({name:$(`#fn${i}`).value,balance:+$(`#fb${i}`).value||0}));save();adminTab('finance')}
function addDoc(){state.documents.push({name:$('#dName').value,url:$('#dUrl').value,category:$('#dCat').value,visibility:$('#dVis').value});save();adminTab('docs')}
async function init(){try{let local=JSON.parse(localStorage.getItem('arraudhahB')||'null');if(local)state={...state,...local,pages:{...state.pages,...local.pages}};let cloud=await surauDb.loadConfig();if(cloud)state={...state,...cloud,pages:{...state.pages,...cloud.pages}}}catch(e){console.warn(e)}applyTheme();render();loadPrayer();setInterval(clock,1000);setInterval(loadPrayer,1800000)}
init();
